### ISSUE TITLE
Fanyi QQ integration

### ISSUE THREAD

**Issue by Fevol** [Fevol/obsidian-translate#11]
(Request from Discord) Implement QQ as a translation service

## Tasks
- [x] Adapt DummyTranslate to use QQ's API
- [x] Add appropriate options to settings page
- [x] Add service info to constants.ts
- [x] Add service info to README.md
