### ISSUE TITLE
Bergamot integration

### ISSUE THREAD

**Issue by Fevol** [Fevol/obsidian-translate#15]
Implement client-side translation via [Bergamot](https://github.com/browsermt/bergamot-translator/), requires minimal set-up for the user.

## Tasks
- [x] Add WASM binary of Bergamot
- [x] Integrate Bergamot into Bergamot translate handler
- [x] Relative loading of WASM and Language Model
- [x] Download button for WASM
- [x] Dropdown to select models to add (determines available languages)
- [x] Download button for any selection of language Model
- [ ] Performance improvements with loading binary and model
- [x] Update models if newer version is found on registry
- [x] Check for binary updates on reload of languages

## Issues
- Loading both the large WASM binary and the language model takes some time (start-up time for Obsidian increased by 0.7s on a speedy computer)
