### ISSUE TITLE
Fasttext integration

### ISSUE THREAD

**Issue by Fevol** [Fevol/obsidian-translate#16]
Implement client-side language detection via the [FastText](https://fasttext.cc/) library

## Tasks
- [x] Add WASM binary of FastText
- [x] Integrate FastText into Bergamot translate handler
- [x] Relative loading of WASM and Language Model
- [x] Download button for WASM and Language Model
- [ ] Allow user to choose which model to use (1MB vs 150MB model - not sure if anybody would want this though)
- [x] Performance improvements with loading binary and model

## Issues
- Loading both the large WASM binary and the language model takes some time (start-up time for Obsidian increased by 0.7s on a speedy computer)
