### ISSUE TITLE
Lingva integration

### ISSUE THREAD

**Issue by Fevol** [Fevol/obsidian-translate#17]
Implement [Lingva](https://github.com/thedaviddelta/lingva-scraper) as a translation service, this service scrapes translations from Google Translate, without accessing any Google services

## Tasks
- [x] Adapt DummyTranslate to use Lingva's API
- [x] Add appropriate options to settings page
- [x] Add service info to constants.ts
- [x] Add service info to README.md

## Issues
Probably not entirely legal
